name: Flake8 Linter

on:
  pull_request:
    branches:
      - dev  # Run only on pull requests to the dev branch

jobs:
  lint:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetches your code

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Adjust based on your Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8  # Install Flake8

      - name: Run Flake8
        run: flake8 . --count --max-line-length=100 --show-source --statistics
